### ISSUE TITLE
What is the purpose of clean-libexec.sh

### ISSUE THREAD

**Issue by magicDGS** [robmaz/distmap#59]
In the root repository, there is a `clean-libexec.sh` script where the purpose is not clear. I recommend to move it to a `scripts/` folder if it is for the management of the repository or to remove it if it's not necessary anymore.

It will be also useful if the script have some comments for the purpose, or a README in the scripts folder is included for explanation.

**Comment by robmaz** [comment]
I think you put that there to do what it says?

**Comment by magicDGS** [comment]
I didn't add that script, but I think that this requires a scripts section for developers (not for users). Otherwise, it is weird in the root directory.

**Comment by robmaz** [comment]
This script was basically a one-time thing to clean out some fluff. But this whole libexec dir is going to go in the next revision, so let us keep it around until then and remove it together with libexec.

**Comment by magicDGS** [comment]
In that case, I open a more explicit issue. Closing in favor of #61
