### ISSUE TITLE
--only-download-trimmed-reads will be broken after ReadTools integration

### ISSUE THREAD

**Issue by magicDGS** [robmaz/distmap#64]
If the reads are trimmed on upload after #53, the `--only-download-trimmed-reads` won't work any longer. There are several options:

* Remove support for the option: the user can trim locally if he wants the reads, and then upload; or perform the whole pipeline and get the reads after mapping, converting back to FASTQ using ReadTools/Picard.
* Add reading support in ReadTools for distmap format. The format will be detected by extension (`.distmap`, and `.tfq` after https://github.com/magicDGS/ReadTools/issues/404). Then, download can be done by just calling any of the "Reads conversion" tools to download as FASTQ or standardized SAM/BAM/CRAM.
* Download using custom scripts to read the format. For `.tfq` will be an easy one-liner; for legacy format, it will require a python/perl script (I think that already implemented)

I am in favor of removing, but it is your decision @robmaz!

**Comment by magicDGS** [comment]
Actually, in #76 I detected that the option is not documented, although in the Wiki is. What should we do with it?

**Comment by robmaz** [comment]
Die when anyone tries to use it and print an "OBSOLETE: Hasn't worked for a
while." message?

2018-02-27 14:35 GMT+01:00 Daniel Gómez-Sánchez <notifications@github.com>:

**Comment by magicDGS** [comment]
I would do that. In addition, I would document in the help adding a short-note saying that because trimming is done while uploading, the user can trim locally if they require the trimmed unmapped reads; otherwise, the mapped files would be trimmed and can be converted to FASTQ using ReadTools or picard.
