### ISSUE TITLE
Decide if samtools or picard is required

### ISSUE THREAD

**Issue by magicDGS** [robmaz/distmap#9]
Currently, both picard and samtools are required. Most of the functionality of samtools is included already in picard, so I suggest to require only picard for DistMap.

In addition, I don't know if after the ReadTools integration Picard is still required, so maybe both of them may be removed...

**Comment by magicDGS** [comment]
This can be done easily after remove suport for separate picard files (see #39) and requiring picard.jar

**Comment by magicDGS** [comment]
Requirements can be found in this experimental branch: https://github.com/robmaz/distmap/tree/dgs_rm_samtools

**Comment by magicDGS** [comment]
I can also bundle the required tools from Picard into ReadTools, which is what actually GATK is doing in its toolkit in version 4.0.0.0 - like that, only the ReadTools binary should be distributed around the workers instead of the Picard one.

Nevertheless, the ReadTools binary is much larger, so maybe there is some problem in that respect.

**Comment by robmaz** [comment]
I am not sure why we need either now. It seems to me that readtools handles everything now. I don't think the workers need picard either?

**Comment by magicDGS** [comment]
In that case I can also have a look to the branch for remove samtools/picard, between today and tomorrow.

**Comment by magicDGS** [comment]
Samtools is already removed. Closing this in favor of #78
